name: Build

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ./math-aggregator.db
            ./math-aggregator.db-journal
          key: ${{ runner.os }}-${{ hashFiles('./math-aggregator.version') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('./math-aggregator.version') }}
      - name: Build
        run: |
          make build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
